//src\client\service\TasksService.ts

import { CancelablePromise, OpenAPI } from "@/client";
import { request as __request } from '@/client/core/request';
import { TableTemplate } from "./tabletemplate";

/**
 * table Task
 *  src\client\models\Task.ts
 * Generated by OpenAPI Generator (https://openapi-generator.tech)
 * class Tasks Client Db Service
 */
export class TemplateClientDbService {

    /**
     * Get all
     * @returns Task Successful Response
     * @throws ApiError
     */
    public static getAll(): CancelablePromise<Array<TableTemplate>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/tasks/',
        });
    }
    
    /**
     * insert
     * @param requestBody
     * @returns Task Successful Response
     * @throws ApiError
     */
    public static insert(requestBody:TableTemplate):CancelablePromise<TableTemplate> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/tasks/',
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                422: `Validation Error`,
            }
        });
    }

    /**
     * Get
     * @param id
     * @returns Task Successful Response
     * @throws ApiError
     */
    public static getById(id:number):CancelablePromise<TableTemplate> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/tasks/{id}',
            path: {'id': id},
            errors: {
                422: `Validation Error`,
            }
        });
    }

    /**
     * Update
     * @param id
     * @param requestBody
     * @returns Task Successful Response
     * @throws ApiError
     */
    public static update(id:number,requestBody:TableTemplate): CancelablePromise<TableTemplate> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/tasks/{id}',
            path: {'id': id},
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                422: `Validation Error`,
            }
        });
    }

    /**
     * Delete
     * @param id
     * @returns Task Successful Response
     * @throws ApiError
     */
    public static delete(id:number):CancelablePromise<TableTemplate> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/tasks/{id}',
            path: {'id': id},
            errors: {
                422: `Validation Error`,
            }
        });
    }

    /**
     * Get by other field
     * @param name
     * @returns Task Successful Response
     * @throws ApiError
     */
    
    public static getByOther(name:string):CancelablePromise<Array<TableTemplate>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/tasks/name/{name}',
            path: {'name':name},
            errors: {
                422: `Validation Error`,
            }
        });
    }
    
    

}//end service
