import type { Metadata } from "next";

import "./globals.css";
import "@/css/monikai.css";
import "@/css/allwidths.css";
import "@icon/themify-icons/themify-icons.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}:Readonly<{children:React.ReactNode;}>) {
  return (
    <html data-theme="darkness" lang="en">
      <body className="flex justify-center">
        {children}
      </body>
    </html>
  );
}
